version: '3'

services:
  chatbot_api:
    build:
      context: ./chatbot_api
    container_name: chatbot_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - chatbot_net

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    container_name: chatbot_frontend
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"
    networks:
      - chatbot_net
networks:
  chatbot_net:
    driver: bridge
